#!/usr/bin/env python3
"""Environment manager for Odoo dev environments.

Usage:
  env_manager.py create NAME [--port PORT] [--odoo 18|19] [--db DBNAME] [--modules modules] [--gits "url1 url2"]
  env_manager.py list
  env_manager.py delete NAME
  env_manager.py open NAME   # prints URL to open
  env_manager.py ui          # generate simple HTML listing

This script:
 - creates a `.env.<NAME>` file with provisioning variables
 - creates a `docker-compose.override.<NAME>.yml` that binds a host port
 - runs `docker compose -p <NAME> -f docker-compose.yml -f docker-compose.override.<NAME>.yml up -d db odoo-<ver>`
 - writes metadata to `environments/envs.json`

Designed to be simple and cross-platform.
"""

import argparse
import json
import os
import shutil
import socket
import subprocess
import sys
import time
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENVS_JSON = os.path.join(ROOT, 'environments', 'envs.json')
DOCKER_COMPOSE = 'docker compose'
DEFAULT_ODOO_VER = '18'
DEFAULT_PORT_START = 8070


def read_envs():
    try:
        with open(ENVS_JSON, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception:
        return []


def write_envs(envs):
    with open(ENVS_JSON, 'w', encoding='utf-8') as f:
        json.dump(envs, f, indent=2)


def find_free_port(start=DEFAULT_PORT_START):
    used = {int(p.split(':')[-1]) for p in get_published_ports()}
    p = start
    while True:
        if p not in used and is_port_free(p):
            return p
        p += 1


def is_port_free(port):
    s = socket.socket()
    try:
        s.bind(('127.0.0.1', port))
        return True
    except OSError:
        return False
    finally:
        try:
            s.close()
        except Exception:
            pass


def get_published_ports():
    try:
        out = subprocess.check_output(['docker', 'ps', '--format', '{{.Ports}}'], text=True)
        ports = []
        for line in out.splitlines():
            # parse host:port->container
            parts = [p.strip() for p in line.split(',') if p.strip()]
            for p in parts:
                if '->' in p and ':' in p:
                    # example: 0.0.0.0:8070->8069/tcp
                    host = p.split('->')[0]
                    if ':' in host:
                        port = host.split(':')[-1]
                        ports.append(port)
        return ports
    except Exception:
        return []


def run(cmd, cwd=ROOT, capture=False):
    print('RUN:', ' '.join(cmd))
    if capture:
        return subprocess.check_output(cmd, cwd=cwd, text=True, stderr=subprocess.STDOUT)
    else:
        subprocess.check_call(cmd, cwd=cwd)


def create_env(name, port=None, odoo_ver=DEFAULT_ODOO_VER, dbname=None, modules=None, gits=None):
    # defaults
    if port is None:
        port = find_free_port()
    project = name
    if dbname is None:
        dbname = f'{name}_db'
    modules = modules or 'webnex_sample'
    gits = gits or ''

    # write .env.<name>
    envfile = os.path.join(ROOT, f'.env.{name}')
    with open(envfile, 'w', encoding='utf-8') as f:
        f.write('# Auto-generated by env_manager.py\n')
        f.write('AUTO_INIT=true\n')
        f.write(f'INIT_DB_NAME={dbname}\n')
        f.write(f'INIT_MODULES={modules}\n')
        f.write(f'INIT_MODULE_GITS={gits}\n')

    # compose override
    override_name = os.path.join(ROOT, f'docker-compose.override.{name}.yml')
    svc = f'odoo-{odoo_ver}'
    override = f"""
services:
  {svc}:
    ports:
      - "{port}:8069"
    env_file:
      - .env.{name}
"""
    with open(override_name, 'w', encoding='utf-8') as f:
        f.write(override)

    # bring up db and odoo for this project
    cmd = ['docker', 'compose', '-p', project, '-f', 'docker-compose.yml', '-f', os.path.basename(override_name), 'up', '-d', 'db', svc]
    run(cmd)

    # wait and check logs for provisioning
    print('Waiting for provisioning to finish (monitor logs)...')
    time.sleep(3)
    for i in range(30):
        try:
            logs = run(['docker', 'compose', '-p', project, '-f', 'docker-compose.yml', '-f', os.path.basename(override_name), 'logs', '--tail', '200', svc], capture=True)
            if 'Running Odoo to install modules' in logs or 'Installing module' in logs or 'Initializing database' in logs:
                print('Provisioning messages detected in logs')
                break
        except Exception:
            pass
        time.sleep(2)

    # record environment
    envs = read_envs()
    env = {
        'name': name,
        'project': project,
        'port': port,
        'odoo_version': odoo_ver,
        'db': dbname,
        'modules': modules.split(','),
        'gits': gits.split() if gits else [],
        'created_at': datetime.utcnow().isoformat() + 'Z'
    }
    envs = [e for e in envs if e.get('name') != name]
    envs.append(env)
    write_envs(envs)
    print('Environment created:', env)
    return env


def list_envs():
    envs = read_envs()
    for e in envs:
        print(f"{e['name']}: port={e['port']} db={e['db']} modules={','.join(e['modules'])}")


def delete_env(name):
    envs = read_envs()
    env = next((e for e in envs if e['name'] == name), None)
    if not env:
        print('Not found:', name)
        return
    project = env['project']
    override = os.path.basename(os.path.join(ROOT, f'docker-compose.override.{name}.yml'))
    print('Stopping and removing compose project:', project)
    run(['docker', 'compose', '-p', project, '-f', 'docker-compose.yml', '-f', override, 'down', '-v'])
    # remove files
    for fname in [os.path.join(ROOT, f'.env.{name}'), os.path.join(ROOT, f'docker-compose.override.{name}.yml')]:
        try:
            os.remove(fname)
        except FileNotFoundError:
            pass
    envs = [e for e in envs if e['name'] != name]
    write_envs(envs)
    print('Deleted environment', name)


def gen_ui():
    envs = read_envs()
    html = ['<html><head><meta charset="utf-8"><title>Environments</title></head><body>']
    html.append('<h1>Environments</h1>')
    html.append('<ul>')
    for e in envs:
        url = f'http://localhost:{e["port"]}/web'
        html.append(f'<li><a href="{url}" target="_blank">{e["name"]}</a> (port {e["port"]}) - DB: {e["db"]} - modules: {','.join(e["modules"])}</li>')
    html.append('</ul>')
    html.append('</body></html>')
    out = os.path.join(ROOT, 'templates', 'environments.html')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, 'w', encoding='utf-8') as f:
        f.write('\n'.join(html))
    print('Generated UI at templates/environments.html')


def main():
    p = argparse.ArgumentParser()
    sub = p.add_subparsers(dest='cmd')
    c = sub.add_parser('create')
    c.add_argument('name')
    c.add_argument('--port', type=int)
    c.add_argument('--odoo', choices=['18', '19'], default=DEFAULT_ODOO_VER)
    c.add_argument('--db')
    c.add_argument('--modules')
    c.add_argument('--gits')

    sub.add_parser('list')
    d = sub.add_parser('delete')
    d.add_argument('name')
    sub.add_parser('open')
    sub.add_parser('ui')

    args = p.parse_args()
    if args.cmd == 'create':
        create_env(args.name, args.port, args.odoo, args.db, args.modules, args.gits)
        gen_ui()
    elif args.cmd == 'list':
        list_envs()
    elif args.cmd == 'delete':
        delete_env(args.name)
        gen_ui()
    elif args.cmd == 'open':
        print('open not implemented, run `python scripts/env_manager.py ui` and open templates/environments.html')
    elif args.cmd == 'ui':
        gen_ui()
    else:
        p.print_help()


if __name__ == '__main__':
    main()
